import './models/meal.dart';

import './models/category.dart';
import 'package:flutter/material.dart';

const DAMMY_CATEGORY = const [
  Categories(id: 'c1', title: 'Italian', color: Colors.purple),
  Categories(id: 'c2', title: 'Quick and Easy', color: Colors.red),
  Categories(id: 'c3', title: 'Myanmar', color: Colors.blue),
  Categories(id: 'c4', title: 'Korean', color: Colors.deepOrangeAccent),
  Categories(id: 'c5', title: 'Asia', color: Colors.orange),
  Categories(id: 'c6', title: 'German', color: Colors.grey),
  Categories(id: 'c7', title: 'Breakfast', color: Colors.cyanAccent),
];

const DAMMY_MEAL = const [
  Meal(
    id: 'm1',
    categories: ['c3'],
    title: 'Chicken Curry',
    imgUrl:
        'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-908515_10-0551430.jpg?quality=90&webp=true&resize=300,272',
    ingredients: [
      '1 large onion',
      '6 garlic cloves, roughly chopped',
      '50g ginger, roughly chopped',
      '4 tbsp vegetable oil',
      '2 tsp cumin seeds',
      '1 tsp fennel seeds',
      '5cm cinnamon stick',
      '1 tsp chilli flakes',
      '1 tsp garam masala',
      '1 tsp turmeric',
      '6 garlic cloves, roughly chopped',
      '50g ginger, roughly chopped',
      '4 tbsp vegetable oil',
      '2 tsp cumin seeds',
      '1 tsp fennel seeds',
      '5cm cinnamon stick',
      '1 tsp chilli flakes',
      '1 tsp garam masala',
      '1 tsp turmeric',
      ''
    ],
    steps: [
      'there’s no need to add any water if you are grating the onion. Tip into a small bowl and leave on one side.',
      'Put 6 roughly chopped garlic cloves and 50g roughly chopped ginger into the same food processor and add 4 tbsp water – process until smooth and spoon into another small bowl. ',
    ],
    duration: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm2',
    categories: ['c1'],
    title: 'Pork Curry',
    imgUrl:
    'https://keyassets-p2.timeincuk.net/wp/prod/wp-content/uploads/sites/53/2017/06/pork-curry.jpg',
    ingredients: [
      '1 large onion',
      '6 garlic cloves, roughly chopped',
      '50g ginger, roughly chopped',
      '4 tbsp vegetable oil',
      '2 tsp cumin seeds',
      '1 tsp fennel seeds',
      '5cm cinnamon stick',
      '1 tsp chilli flakes',
      '1 tsp garam masala',
      '1 tsp turmeric',
      '6 garlic cloves, roughly chopped',
      '50g ginger, roughly chopped',
      '4 tbsp vegetable oil',
      '2 tsp cumin seeds',
      '1 tsp fennel seeds',
      '5cm cinnamon stick',
      '1 tsp chilli flakes',
      '1 tsp garam masala',
      '1 tsp turmeric',
      ''
    ],
    steps: [
      'there’s no need to add any water if you are grating the onion. Tip into a small bowl and leave on one side.',
      'Put 6 roughly chopped garlic cloves and 50g roughly chopped ginger into the same food processor and add 4 tbsp water – process until smooth and spoon into another small bowl. ',
    ],
    duration: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm3',
    categories: ['c6'],
    title: 'WW Curry',
    imgUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-908515_10-0551430.jpg?quality=90&webp=true&resize=300,272',
    ingredients: [
      '1 large onion',
      '6 garlic cloves, roughly chopped',
      '50g ginger, roughly chopped',
      '4 tbsp vegetable oil',
      '2 tsp cumin seeds',
      '1 tsp fennel seeds',
      '5cm cinnamon stick',
      '1 tsp chilli flakes',
      '1 tsp garam masala',
      '1 tsp turmeric',
      '6 garlic cloves, roughly chopped',
      '50g ginger, roughly chopped',
      '4 tbsp vegetable oil',
      '2 tsp cumin seeds',
      '1 tsp fennel seeds',
      '5cm cinnamon stick',
      '1 tsp chilli flakes',
      '1 tsp garam masala',
      '1 tsp turmeric',
      ''
    ],
    steps: [
      'there’s no need to add any water if you are grating the onion. Tip into a small bowl and leave on one side.',
      'Put 6 roughly chopped garlic cloves and 50g roughly chopped ginger into the same food processor and add 4 tbsp water – process until smooth and spoon into another small bowl. ',
    ],
    duration: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm',
    categories: ['c3'],
    title: 'Chicken Curry',
    imgUrl:
    'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-908515_10-0551430.jpg?quality=90&webp=true&resize=300,272',
    ingredients: [
      '1 large onion',
      '6 garlic cloves, roughly chopped',
      '50g ginger, roughly chopped',
      '4 tbsp vegetable oil',
      '2 tsp cumin seeds',
      '1 tsp fennel seeds',
      '5cm cinnamon stick',
      '1 tsp chilli flakes',
      '1 tsp garam masala',
      '1 tsp turmeric',
      '6 garlic cloves, roughly chopped',
      '50g ginger, roughly chopped',
      '4 tbsp vegetable oil',
      '2 tsp cumin seeds',
      '1 tsp fennel seeds',
      '5cm cinnamon stick',
      '1 tsp chilli flakes',
      '1 tsp garam masala',
      '1 tsp turmeric',
      ''
    ],
    steps: [
      'there’s no need to add any water if you are grating the onion. Tip into a small bowl and leave on one side.',
      'Put 6 roughly chopped garlic cloves and 50g roughly chopped ginger into the same food processor and add 4 tbsp water – process until smooth and spoon into another small bowl. ',
    ],
    duration: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
];
